### ISSUE TITLE
about last quistion in evry levle

### ISSUE THREAD

**Issue by elomoery** [Erkapos/WonderWord#2]
please
can  i ask  why dose not go to score screen directly?
i cant access to score screen
 Please edit
We must go to the result screen immediately after completing the answer to the last question of each level
But this only happens if we click on the finish button

**Comment by Erkapos** [comment]
for this one, its true that we need to press the finish button first to get
to the result screen. i can edit that later.

**Comment by elomoery** [comment]
please snd  this  edit   now ineed it please try
elomoery@gmail.com

**Comment by Erkapos** [comment]
issue solved
